config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :products

  get '/foods/:id/edit' => 'food#edit'









end

app/models/component.rb
class Component < ActiveRecord::Base
  has_many :foods, through: :foods_data
  belongs_to :component_types, foreign_key: "component_type_id"
end

app/models/component_type.rb
class ComponentType < ActiveRecord::Base
  has_many :components

end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :components, through: :foods_data
end

app/models/foods_datum.rb
class FoodsDatum < ActiveRecord::Base
  belongs_to :foods, foreign_key: "food_id" 
  belongs_to :components, foreign_key: "component_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_properties
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        format.html { redirect_to @food,
          notice: 'Food was successfully created.'
        }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # This method identifies the relationships between Food and ComponentType,
  # so those relationships can be rendered by the view.
  def set_properties
    @components_all = {}
    # Store all components within a hass named after the ComponentType.name
    ComponentType.all.each do |ct|
      @components_all[ct.name] = Component.where(component_types_id: ct.id)
    end
    product_components if params[:id]
  end

  def product_components
    @product_components = {}
    @components_all.keys.each do |ctn|
      @product_components[ctn] = []
    end
    FoodsDatum.where(foods_id: params[:id]).each do |fd|
      @product_components[
        ComponentType.find(
          Component.find(fd.components_id)
          .component_types_id).name].append Component.find(fd.components_id)
    end
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def food_params
    params.require(:food).permit(
      :name, :description, :properties,
      :vitamins, :carbs, :fats, :minerals, :proteins)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>

  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_area :properties %>
  </div>
  <div class="field">    
    <table>
    <tr>
    <% @components_all.keys.each do |ctname| %>    
    <th>
    <%= f.label ctname %><br>
    </th>
    <% end %>
    </tr>
    <% @components_all_lengths = {} %>
    <% @components_all.keys.each do |ctname| %>
    <% @components_all_lengths[ctname] = ctname.length%>
    <% end %>
    <% @larger_key = @components_all_lengths.max_by{|k,v| v} %>
    <% for component in 0..@larger_key[1] %>
      <tr>
      <% @components_all.keys.each do |ctname| %>    
      <td>
        <% if @components_all[ctname][component]%>
          <% if params[:id] %>
          <%= 
            check_box_tag @components_all[ctname][component].name, 'yes', (@product_components[ctname].include? @components_all[ctname][component])
          %>
          <% else %>
          <%= 
            check_box_tag @components_all[ctname][component].name, 'yes'
          %>
          <% end %>
        <%= @components_all[ctname][component].name %>
      <% end%>
    </td>
    <% end %>
      </tr>  
    <% end %>
  </table>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.properties %></td>
        <td><%= @related %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @food.properties %>
</p>
<table>
  <tr>
  <% @components_all.keys.each do |ctname| %>    
    <th>
    <%= ctname %><br>
    </th>
  <% end %>
  </tr>
  <% @components_all.keys.each do |ctname| %>
  <tr>
    <% @components_all[ctname].each do |component| %>
    <td>
      <% if params[:id] %>
        <% if (@product_components[ctname].include? component) %>
          <%= component.name %>
        <% else %>
      
        <% end %>
      <% end %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodMonitor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>